version: "3.8"

services:
  postgres:
    image: postgres:13.6
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      - back
    ports:
      - "5432:5432"

  backend:
    image: gabray/socrud
    depends_on: [postgres]
    networks:
      - back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/socrud"

networks:
  back: {}